### ISSUE TITLE
[Question] Allowing server side only installation

### ISSUE THREAD

**Issue by TerdyTheTerd** [JackFred2/WhereIsIt#3]
Working on a Vanilla client friendly server, and I was wondering if for this mod it's possible to instead of doing any custom rendering, you would rather send a play/spawn packet to the client of whatever particle/effect makes the most sense at the containers location.

If this is not a feature you are willing/able to add, what are your thoughts on allowing for a custom fork to be made that does that (won't be distributed anywhere since its only running on the server).

**Comment by JackFred2** [comment]
The mod shouldn't prevent vanila clients from working; they just wouldn't be able to use the mod (Fabric clients with the mod would still work just fine).
The most likely implementation for vanilla clients would be placing a NoAI slime or similar with glowing at the inventory locations, since particles dont show through walls, and a `/search <hand|item id>` command - possible and maybe in the future, but would take a bit to get working.
As for forking the project, as long as you follow the [MIT license terms](https://choosealicense.com/licenses/mit/) (i.e. keep the LICENSE file intact) you're free to fork/modify/distribute.

**Comment by TerdyTheTerd** [comment]
Cool, that was pretty much what I was going to do. I implemented a basic one last night, just need to make the particles fancier by circling around the container or something, and add in the rest of the command to search by item name/tag 👍 

Current basic usage when using `/find` to look for whatever item is in the players hand
![image](https://user-images.githubusercontent.com/9743432/100527346-5624b100-3197-11eb-9753-23fd44453676.png)
